section: screens
	DESKTOP-DTEKPKA:
	MAC:
end

section: aliases
end

section: links
	DESKTOP-DTEKPKA:
		down(0,37) = MAC(0,100)
	MAC:
		up(0,100) = DESKTOP-DTEKPKA(0,37)
end

section: options
	protocol = barrier
	relativeMouseMoves = false
	win32KeepForeground = false
	defaultLockToScreenState = false
	disableLockToScreen = false
	clipboardSharing = false
	clipboardSharingSize = 3072
	switchCorners = none
	switchCornerSize = 0
end