[core]
computerName=DESKTOP-DTEKPKA
lastVersion=1.26.0.0
coreMode=0

[internalConfig]
numColumns=5
numRows=3
hasHeartbeat=false
heartbeat=5000
protocol=1
relativeMouseMoves=false
win32KeepForeground=false
hasSwitchDelay=false
switchDelay=250
hasSwitchDoubleTap=false
switchDoubleTap=250
switchCornerSize=0
defaultLockToScreenState=false
disableLockToScreen=false
clipboardSharing=false
clipboardSharingSize=3072
switchCornerArray\1\switchCorner=false
switchCornerArray\2\switchCorner=false
switchCornerArray\3\switchCorner=false
switchCornerArray\4\switchCorner=false
switchCornerArray\size=4
screens\1\name=DESKTOP-DTEKPKA
screens\2\name=
screens\3\name=
screens\4\name=
screens\5\name=
screens\6\name=MAC
screens\7\name=
screens\8\name=
screens\9\name=
screens\10\name=
screens\11\name=
screens\12\name=
screens\13\name=
screens\14\name=
screens\15\name=
screens\size=15
hotkeys\size=0

[gui]
logExpanded=true
